apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fermentation-station-agent-lb-testing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lukasb27/fermentation-station-agent.git
    targetRevision: lb-testing
    path: k8s
    kustomize:
      images:
        - lukasball/fermentation-station-agent=lukasball/fermentation-station-agent:lb-testing
      commonAnnotations:
        prNumber: "26"
        sha: 11d5dac7e8f1a528004dfba71e89ebe90b56eeb5
  destination:
    server: https://kubernetes.default.svc
    namespace: lb-testing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true